on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/github-script@v8
        with:
          script: |
            function add(a: number, b: number): number {
                return a + b;
            }

            core.info(add(1, 41))

            const utils = await import('./utils.ts')

            core.info(utils.add(1, 41))
